# Generated by Django 5.2.8 on 2025-12-01 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='customer', editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Multivendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.PositiveBigIntegerField()),
                ('restaurant_lic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('restaurant_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user_type', models.CharField(default='vendor', editable=False, max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
