# Generated by Django 5.2.8 on 2025-12-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
