# Generated by Django 5.2.4 on 2025-12-05 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0003_remove_multivendors_vendor_name_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multivendors', to='vendorapp.multivendors')),
            ],
        ),
    ]
