# Generated by Django 5.2.4 on 2025-12-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0005_alter_fooditems_vendor_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivendors',
            name='franchise',
            field=models.BooleanField(default=False),
        ),
    ]
